# Generated by Django 3.2.11 on 2022-01-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('rating', models.FloatField()),
                ('is_top_250', models.BooleanField(default=False)),
                ('top_250_order', models.IntegerField(default=0)),
                ('is_most_popular', models.BooleanField(default=False)),
                ('most_popular_order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=512)),
                ('detail_url', models.URLField()),
                ('image', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
